[project]
name = "gpt2-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MrudhuhasM", email = "mrudhuhas@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
]

[project.scripts]
gpt2-engine = "gpt2_engine:main"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
